export const titleNames = [
  { value: "นาย", label: "นาย" },
  { value: "นาง", label: "นาง" },
  { value: "นางสาว", label: "นางสาว" },
  { value: "ดร.", label: "ดร." },
  { value: "ผศ.", label: "ผศ." },
  { value: "รศ.", label: "รศ." },
  { value: "ศ.", label: "ศ." },
  { value: "อาจารย์", label: "อาจารย์" },
  { value: "พล.ต.อ.", label: "พล.ต.อ." },
  { value: "พล.อ.", label: "พล.อ." },
  { value: "ม.ล.", label: "ม.ล." },
  { value: "ม.ร.ว.", label: "ม.ร.ว." },
  { value: "พล.ต.ท.", label: "พล.ต.ท." },
  { value: "พล.ต.ต.", label: "พล.ต.ต." },
  { value: "พ.ต.อ.", label: "พ.ต.อ." },
  { value: "พ.ต.ท.", label: "พ.ต.ท." },
  { value: "พ.ต.ต.", label: "พ.ต.ต." },
  { value: "ร.ต.อ.", label: "ร.ต.อ." },
  { value: "ร.ต.ท.", label: "ร.ต.ท." },
  { value: "ร.ต.ต.", label: "ร.ต.ต." },
  { value: "ร.ต.", label: "ร.ต." },
  { value: "ร.ท.", label: "ร.ท." },
  { value: "ร.อ.", label: "ร.อ." },
  { value: "จ.ส.อ.", label: "จ.ส.อ." },
  { value: "จ.ส.ท.", label: "จ.ส.ท." },
  { value: "จ.ส.ต.", label: "จ.ส.ต." },
];
